---
functional:
  - требование 3
  - требование 4
  - требование 5
  - требование 6
  - требование 8
  - требование 9
non-functional:
  - требование 1
  - требование 2
  - требование 7
implicit:
  - требование 10
  - Пользователь должен иметь возможность проходить регистрацию и авторизацию на сайте
  - Пользовательно должен иметь возможность добавлять товары в "Список желаний" для последующего их просмотра
  - На сайте после оформления заказа, должно появляться окно со способами оплаты, для ее произведения
